gesture = 3, horizontal, workspace
exec-once = swaybg -i /home/emal0n/Imagens/wall.png -m fill
bind = SUPER, C, togglefloating
bind = SUPER, C, resizeactive, exact 60% 70%
bind = SUPER, C, centerwindow

# jetbrains
windowrule = center true, match:class jetbrains-.*, match:title splash, match:float true
windowrule = no_focus true, match:class jetbrains-.*, match:title splash, match:float true

windowrule = no_focus true, match:class jetbrains-.*, match:title win.*, match:float true

windowrule = no_blur true, match:class jetbrains-.*, match:float true
windowrule = no_initial_focus true, match:class jetbrains-.*, match:float true
